### ISSUE TITLE
saldns01 and saldns02 are down

### ISSUE THREAD

**Issue by junkurihara** [junkurihara/experimental-resolvers#3]
Currently, the two servers are offline due to unexpected behavior. Their OS are suddenly becoming unresponsive after several hours from bootstrap. Checking the detail of the issue.

**Comment by junkurihara** [comment]
They are back now after totally upgrading the system to Ubuntu 22.04 and new docker. I guess something is wrong after `apt update && apt dist-upgrade` in the old system. Not sure...

Anyways, we need to constantly check if they are healthy for a while.

**Comment by jedisct1** [comment]
Are they? The keys seems to have changed:

```text
2022/07/26 12:55:24 [2.dnscrypt-cert.saldns02.typeq.org.] incorrect signature

Cannot make the DNS request: failed to fetch certificate info from sdns://AQcAAAAAAAAAFTEzMy4xMzAuMTE4LjEwMzo1MDQ0MyCo72atOPI72UkQcaypJBmUUd1btQTwm1VRxHLioOo19SIyLmRuc2NyeXB0LWNlcnQuc2FsZG5zMDIudHlwZXEub3Jn
cause: no useable certificate found
```

**Comment by junkurihara** [comment]
@jedisct1 

Thanks! I didn't know they had changed. Maybe some files are gone due to the trouble. Just fixed them.
